package lemurs.projetlemurs;
// Generated 5 déc. 2017 15:52:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaxonomiBase generated by hbm2java
 */
@Entity
@Table(name="taxonomi_base"
    ,schema="public"
)
public class TaxonomiBase  implements java.io.Serializable {


     private int idtaxonomibase;
     private String higherclassification;
     private String kingdom;
     private String phylum;
     private String dwcclass;
     private String dwcorder;
     private String dwcfamily;
     private String genus;
     private String genussource;
     private String specificepithet;
     private String specificepithetsource;
     private String infraspecificepithet;
     private String infraspecificepithetsource;
     private String scientificname;
     private String scientificnameauthorship;
     private String acceptednameusage;
     private String basisofrecord;
     private String frenchvernacularname;
     private String malagasyvernacularname;
     private String englishvernacularname;
     private String habitatFr;
     private String habitatEn;
     private String habitatsource;
     private String ecologyFr;
     private String ecologyEn;
     private String ecologysource;
     private String behaviorFr;
     private String behaviorEn;
     private String behaviorsource;
     private String threatFr;
     private String threatEn;
     private String threatsource;
     private String morphologyFr;
     private String morphologyEn;
     private String protectedareaoccurrences;

    public TaxonomiBase() {
    }

	
    public TaxonomiBase(int idtaxonomibase) {
        this.idtaxonomibase = idtaxonomibase;
    }
    public TaxonomiBase(int idtaxonomibase, String higherclassification, String kingdom, String phylum, String dwcclass, String dwcorder, String dwcfamily, String genus, String genussource, String specificepithet, String specificepithetsource, String infraspecificepithet, String infraspecificepithetsource, String scientificname, String scientificnameauthorship, String acceptednameusage, String basisofrecord, String frenchvernacularname, String malagasyvernacularname, String englishvernacularname, String habitatFr, String habitatEn, String habitatsource, String ecologyFr, String ecologyEn, String ecologysource, String behaviorFr, String behaviorEn, String behaviorsource, String threatFr, String threatEn, String threatsource, String morphologyFr, String morphologyEn, String protectedareaoccurrences) {
       this.idtaxonomibase = idtaxonomibase;
       this.higherclassification = higherclassification;
       this.kingdom = kingdom;
       this.phylum = phylum;
       this.dwcclass = dwcclass;
       this.dwcorder = dwcorder;
       this.dwcfamily = dwcfamily;
       this.genus = genus;
       this.genussource = genussource;
       this.specificepithet = specificepithet;
       this.specificepithetsource = specificepithetsource;
       this.infraspecificepithet = infraspecificepithet;
       this.infraspecificepithetsource = infraspecificepithetsource;
       this.scientificname = scientificname;
       this.scientificnameauthorship = scientificnameauthorship;
       this.acceptednameusage = acceptednameusage;
       this.basisofrecord = basisofrecord;
       this.frenchvernacularname = frenchvernacularname;
       this.malagasyvernacularname = malagasyvernacularname;
       this.englishvernacularname = englishvernacularname;
       this.habitatFr = habitatFr;
       this.habitatEn = habitatEn;
       this.habitatsource = habitatsource;
       this.ecologyFr = ecologyFr;
       this.ecologyEn = ecologyEn;
       this.ecologysource = ecologysource;
       this.behaviorFr = behaviorFr;
       this.behaviorEn = behaviorEn;
       this.behaviorsource = behaviorsource;
       this.threatFr = threatFr;
       this.threatEn = threatEn;
       this.threatsource = threatsource;
       this.morphologyFr = morphologyFr;
       this.morphologyEn = morphologyEn;
       this.protectedareaoccurrences = protectedareaoccurrences;
    }
   
     @Id 

    
    @Column(name="idtaxonomibase", unique=true, nullable=false)
    public int getIdtaxonomibase() {
        return this.idtaxonomibase;
    }
    
    public void setIdtaxonomibase(int idtaxonomibase) {
        this.idtaxonomibase = idtaxonomibase;
    }

    
    @Column(name="higherclassification")
    public String getHigherclassification() {
        return this.higherclassification;
    }
    
    public void setHigherclassification(String higherclassification) {
        this.higherclassification = higherclassification;
    }

    
    @Column(name="kingdom")
    public String getKingdom() {
        return this.kingdom;
    }
    
    public void setKingdom(String kingdom) {
        this.kingdom = kingdom;
    }

    
    @Column(name="phylum")
    public String getPhylum() {
        return this.phylum;
    }
    
    public void setPhylum(String phylum) {
        this.phylum = phylum;
    }

    
    @Column(name="dwcclass")
    public String getDwcclass() {
        return this.dwcclass;
    }
    
    public void setDwcclass(String dwcclass) {
        this.dwcclass = dwcclass;
    }

    
    @Column(name="dwcorder")
    public String getDwcorder() {
        return this.dwcorder;
    }
    
    public void setDwcorder(String dwcorder) {
        this.dwcorder = dwcorder;
    }

    
    @Column(name="dwcfamily")
    public String getDwcfamily() {
        return this.dwcfamily;
    }
    
    public void setDwcfamily(String dwcfamily) {
        this.dwcfamily = dwcfamily;
    }

    
    @Column(name="genus")
    public String getGenus() {
        return this.genus;
    }
    
    public void setGenus(String genus) {
        this.genus = genus;
    }

    
    @Column(name="genussource")
    public String getGenussource() {
        return this.genussource;
    }
    
    public void setGenussource(String genussource) {
        this.genussource = genussource;
    }

    
    @Column(name="specificepithet")
    public String getSpecificepithet() {
        return this.specificepithet;
    }
    
    public void setSpecificepithet(String specificepithet) {
        this.specificepithet = specificepithet;
    }

    
    @Column(name="specificepithetsource")
    public String getSpecificepithetsource() {
        return this.specificepithetsource;
    }
    
    public void setSpecificepithetsource(String specificepithetsource) {
        this.specificepithetsource = specificepithetsource;
    }

    
    @Column(name="infraspecificepithet")
    public String getInfraspecificepithet() {
        return this.infraspecificepithet;
    }
    
    public void setInfraspecificepithet(String infraspecificepithet) {
        this.infraspecificepithet = infraspecificepithet;
    }

    
    @Column(name="infraspecificepithetsource")
    public String getInfraspecificepithetsource() {
        return this.infraspecificepithetsource;
    }
    
    public void setInfraspecificepithetsource(String infraspecificepithetsource) {
        this.infraspecificepithetsource = infraspecificepithetsource;
    }

    
    @Column(name="scientificname")
    public String getScientificname() {
        return this.scientificname;
    }
    
    public void setScientificname(String scientificname) {
        this.scientificname = scientificname;
    }

    
    @Column(name="scientificnameauthorship")
    public String getScientificnameauthorship() {
        return this.scientificnameauthorship;
    }
    
    public void setScientificnameauthorship(String scientificnameauthorship) {
        this.scientificnameauthorship = scientificnameauthorship;
    }

    
    @Column(name="acceptednameusage")
    public String getAcceptednameusage() {
        return this.acceptednameusage;
    }
    
    public void setAcceptednameusage(String acceptednameusage) {
        this.acceptednameusage = acceptednameusage;
    }

    
    @Column(name="basisofrecord")
    public String getBasisofrecord() {
        return this.basisofrecord;
    }
    
    public void setBasisofrecord(String basisofrecord) {
        this.basisofrecord = basisofrecord;
    }

    
    @Column(name="frenchvernacularname")
    public String getFrenchvernacularname() {
        return this.frenchvernacularname;
    }
    
    public void setFrenchvernacularname(String frenchvernacularname) {
        this.frenchvernacularname = frenchvernacularname;
    }

    
    @Column(name="malagasyvernacularname")
    public String getMalagasyvernacularname() {
        return this.malagasyvernacularname;
    }
    
    public void setMalagasyvernacularname(String malagasyvernacularname) {
        this.malagasyvernacularname = malagasyvernacularname;
    }

    
    @Column(name="englishvernacularname")
    public String getEnglishvernacularname() {
        return this.englishvernacularname;
    }
    
    public void setEnglishvernacularname(String englishvernacularname) {
        this.englishvernacularname = englishvernacularname;
    }

    
    @Column(name="habitat_fr")
    public String getHabitatFr() {
        return this.habitatFr;
    }
    
    public void setHabitatFr(String habitatFr) {
        this.habitatFr = habitatFr;
    }

    
    @Column(name="habitat_en")
    public String getHabitatEn() {
        return this.habitatEn;
    }
    
    public void setHabitatEn(String habitatEn) {
        this.habitatEn = habitatEn;
    }

    
    @Column(name="habitatsource")
    public String getHabitatsource() {
        return this.habitatsource;
    }
    
    public void setHabitatsource(String habitatsource) {
        this.habitatsource = habitatsource;
    }

    
    @Column(name="ecology_fr")
    public String getEcologyFr() {
        return this.ecologyFr;
    }
    
    public void setEcologyFr(String ecologyFr) {
        this.ecologyFr = ecologyFr;
    }

    
    @Column(name="ecology_en")
    public String getEcologyEn() {
        return this.ecologyEn;
    }
    
    public void setEcologyEn(String ecologyEn) {
        this.ecologyEn = ecologyEn;
    }

    
    @Column(name="ecologysource")
    public String getEcologysource() {
        return this.ecologysource;
    }
    
    public void setEcologysource(String ecologysource) {
        this.ecologysource = ecologysource;
    }

    
    @Column(name="behavior_fr")
    public String getBehaviorFr() {
        return this.behaviorFr;
    }
    
    public void setBehaviorFr(String behaviorFr) {
        this.behaviorFr = behaviorFr;
    }

    
    @Column(name="behavior_en")
    public String getBehaviorEn() {
        return this.behaviorEn;
    }
    
    public void setBehaviorEn(String behaviorEn) {
        this.behaviorEn = behaviorEn;
    }

    
    @Column(name="behaviorsource")
    public String getBehaviorsource() {
        return this.behaviorsource;
    }
    
    public void setBehaviorsource(String behaviorsource) {
        this.behaviorsource = behaviorsource;
    }

    
    @Column(name="threat_fr")
    public String getThreatFr() {
        return this.threatFr;
    }
    
    public void setThreatFr(String threatFr) {
        this.threatFr = threatFr;
    }

    
    @Column(name="threat_en")
    public String getThreatEn() {
        return this.threatEn;
    }
    
    public void setThreatEn(String threatEn) {
        this.threatEn = threatEn;
    }

    
    @Column(name="threatsource")
    public String getThreatsource() {
        return this.threatsource;
    }
    
    public void setThreatsource(String threatsource) {
        this.threatsource = threatsource;
    }

    
    @Column(name="morphology_fr")
    public String getMorphologyFr() {
        return this.morphologyFr;
    }
    
    public void setMorphologyFr(String morphologyFr) {
        this.morphologyFr = morphologyFr;
    }

    
    @Column(name="morphology_en")
    public String getMorphologyEn() {
        return this.morphologyEn;
    }
    
    public void setMorphologyEn(String morphologyEn) {
        this.morphologyEn = morphologyEn;
    }

    
    @Column(name="protectedareaoccurrences")
    public String getProtectedareaoccurrences() {
        return this.protectedareaoccurrences;
    }
    
    public void setProtectedareaoccurrences(String protectedareaoccurrences) {
        this.protectedareaoccurrences = protectedareaoccurrences;
    }




}


