package org.wcs.lemurs.model;
// Generated 5 d�c. 2017 15:52:27 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaxonomiBase generated by hbm2java
 */
@Entity
@Table(name = "taxonomi_base")
public class TaxonomiBase {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private int idtaxonomibase;
    
    private String higherclassification;
    private String kingdom;
    private String phylum;
    private String dwcclass;
    private String dwcorder;
    private String dwcfamily;
    private String genus;
    private String genussource;
    private String specificepithet;
    private String specificepithetsource;
    private String infraspecificepithet;
    private String infraspecificepithetsource;
    private String scientificname;
    private String scientificnameauthorship;
    private String acceptednameusage;
    private String basisofrecord;
    private String frenchvernacularname;
    private String malagasyvernacularname;
    private String englishvernacularname;
    private String habitatFr;
    private String habitatEn;
    private String habitatsource;
    private String ecologyFr;
    private String ecologyEn;
    private String ecologysource;
    private String behaviorFr;
    private String behaviorEn;
    private String behaviorsource;
    private String threatFr;
    private String threatEn;
    private String threatsource;
    private String morphologyFr;
    private String morphologyEn;
    private String protectedareaoccurrences;

    public TaxonomiBase() {
    }

    public TaxonomiBase(int idtaxonomibase) {
        this.idtaxonomibase = idtaxonomibase;
    }

    public TaxonomiBase(int idtaxonomibase, String higherclassification, String kingdom, String phylum, String dwcclass, String dwcorder, String dwcfamily, String genus, String genussource, String specificepithet, String specificepithetsource, String infraspecificepithet, String infraspecificepithetsource, String scientificname, String scientificnameauthorship, String acceptednameusage, String basisofrecord, String frenchvernacularname, String malagasyvernacularname, String englishvernacularname, String habitatFr, String habitatEn, String habitatsource, String ecologyFr, String ecologyEn, String ecologysource, String behaviorFr, String behaviorEn, String behaviorsource, String threatFr, String threatEn, String threatsource, String morphologyFr, String morphologyEn, String protectedareaoccurrences) {
        this.idtaxonomibase = idtaxonomibase;
        this.higherclassification = higherclassification;
        this.kingdom = kingdom;
        this.phylum = phylum;
        this.dwcclass = dwcclass;
        this.dwcorder = dwcorder;
        this.dwcfamily = dwcfamily;
        this.genus = genus;
        this.genussource = genussource;
        this.specificepithet = specificepithet;
        this.specificepithetsource = specificepithetsource;
        this.infraspecificepithet = infraspecificepithet;
        this.infraspecificepithetsource = infraspecificepithetsource;
        this.scientificname = scientificname;
        this.scientificnameauthorship = scientificnameauthorship;
        this.acceptednameusage = acceptednameusage;
        this.basisofrecord = basisofrecord;
        this.frenchvernacularname = frenchvernacularname;
        this.malagasyvernacularname = malagasyvernacularname;
        this.englishvernacularname = englishvernacularname;
        this.habitatFr = habitatFr;
        this.habitatEn = habitatEn;
        this.habitatsource = habitatsource;
        this.ecologyFr = ecologyFr;
        this.ecologyEn = ecologyEn;
        this.ecologysource = ecologysource;
        this.behaviorFr = behaviorFr;
        this.behaviorEn = behaviorEn;
        this.behaviorsource = behaviorsource;
        this.threatFr = threatFr;
        this.threatEn = threatEn;
        this.threatsource = threatsource;
        this.morphologyFr = morphologyFr;
        this.morphologyEn = morphologyEn;
        this.protectedareaoccurrences = protectedareaoccurrences;
    }

    public int getIdtaxonomibase() {
        return idtaxonomibase;
    }

    public void setIdtaxonomibase(int idtaxonomibase) {
        this.idtaxonomibase = idtaxonomibase;
    }

    public String getHigherclassification() {
        return higherclassification;
    }

    public void setHigherclassification(String higherclassification) {
        this.higherclassification = higherclassification;
    }

    public String getKingdom() {
        return kingdom;
    }

    public void setKingdom(String kingdom) {
        this.kingdom = kingdom;
    }

    public String getPhylum() {
        return phylum;
    }

    public void setPhylum(String phylum) {
        this.phylum = phylum;
    }

    public String getDwcclass() {
        return dwcclass;
    }

    public void setDwcclass(String dwcclass) {
        this.dwcclass = dwcclass;
    }

    public String getDwcorder() {
        return dwcorder;
    }

    public void setDwcorder(String dwcorder) {
        this.dwcorder = dwcorder;
    }

    public String getDwcfamily() {
        return dwcfamily;
    }

    public void setDwcfamily(String dwcfamily) {
        this.dwcfamily = dwcfamily;
    }

    public String getGenus() {
        return genus;
    }

    public void setGenus(String genus) {
        this.genus = genus;
    }

    public String getGenussource() {
        return genussource;
    }

    public void setGenussource(String genussource) {
        this.genussource = genussource;
    }

    public String getSpecificepithet() {
        return specificepithet;
    }

    public void setSpecificepithet(String specificepithet) {
        this.specificepithet = specificepithet;
    }

    public String getSpecificepithetsource() {
        return specificepithetsource;
    }

    public void setSpecificepithetsource(String specificepithetsource) {
        this.specificepithetsource = specificepithetsource;
    }

    public String getInfraspecificepithet() {
        return infraspecificepithet;
    }

    public void setInfraspecificepithet(String infraspecificepithet) {
        this.infraspecificepithet = infraspecificepithet;
    }

    public String getInfraspecificepithetsource() {
        return infraspecificepithetsource;
    }

    public void setInfraspecificepithetsource(String infraspecificepithetsource) {
        this.infraspecificepithetsource = infraspecificepithetsource;
    }

    public String getScientificname() {
        return scientificname;
    }

    public void setScientificname(String scientificname) {
        this.scientificname = scientificname;
    }

    public String getScientificnameauthorship() {
        return scientificnameauthorship;
    }

    public void setScientificnameauthorship(String scientificnameauthorship) {
        this.scientificnameauthorship = scientificnameauthorship;
    }

    public String getAcceptednameusage() {
        return acceptednameusage;
    }

    public void setAcceptednameusage(String acceptednameusage) {
        this.acceptednameusage = acceptednameusage;
    }

    public String getBasisofrecord() {
        return basisofrecord;
    }

    public void setBasisofrecord(String basisofrecord) {
        this.basisofrecord = basisofrecord;
    }

    public String getFrenchvernacularname() {
        return frenchvernacularname;
    }

    public void setFrenchvernacularname(String frenchvernacularname) {
        this.frenchvernacularname = frenchvernacularname;
    }

    public String getMalagasyvernacularname() {
        return malagasyvernacularname;
    }

    public void setMalagasyvernacularname(String malagasyvernacularname) {
        this.malagasyvernacularname = malagasyvernacularname;
    }

    public String getEnglishvernacularname() {
        return englishvernacularname;
    }

    public void setEnglishvernacularname(String englishvernacularname) {
        this.englishvernacularname = englishvernacularname;
    }

    public String getHabitatFr() {
        return habitatFr;
    }

    public void setHabitatFr(String habitatFr) {
        this.habitatFr = habitatFr;
    }

    public String getHabitatEn() {
        return habitatEn;
    }

    public void setHabitatEn(String habitatEn) {
        this.habitatEn = habitatEn;
    }

    public String getHabitatsource() {
        return habitatsource;
    }

    public void setHabitatsource(String habitatsource) {
        this.habitatsource = habitatsource;
    }

    public String getEcologyFr() {
        return ecologyFr;
    }

    public void setEcologyFr(String ecologyFr) {
        this.ecologyFr = ecologyFr;
    }

    public String getEcologyEn() {
        return ecologyEn;
    }

    public void setEcologyEn(String ecologyEn) {
        this.ecologyEn = ecologyEn;
    }

    public String getEcologysource() {
        return ecologysource;
    }

    public void setEcologysource(String ecologysource) {
        this.ecologysource = ecologysource;
    }

    public String getBehaviorFr() {
        return behaviorFr;
    }

    public void setBehaviorFr(String behaviorFr) {
        this.behaviorFr = behaviorFr;
    }

    public String getBehaviorEn() {
        return behaviorEn;
    }

    public void setBehaviorEn(String behaviorEn) {
        this.behaviorEn = behaviorEn;
    }

    public String getBehaviorsource() {
        return behaviorsource;
    }

    public void setBehaviorsource(String behaviorsource) {
        this.behaviorsource = behaviorsource;
    }

    public String getThreatFr() {
        return threatFr;
    }

    public void setThreatFr(String threatFr) {
        this.threatFr = threatFr;
    }

    public String getThreatEn() {
        return threatEn;
    }

    public void setThreatEn(String threatEn) {
        this.threatEn = threatEn;
    }

    public String getThreatsource() {
        return threatsource;
    }

    public void setThreatsource(String threatsource) {
        this.threatsource = threatsource;
    }

    public String getMorphologyFr() {
        return morphologyFr;
    }

    public void setMorphologyFr(String morphologyFr) {
        this.morphologyFr = morphologyFr;
    }

    public String getMorphologyEn() {
        return morphologyEn;
    }

    public void setMorphologyEn(String morphologyEn) {
        this.morphologyEn = morphologyEn;
    }

    public String getProtectedareaoccurrences() {
        return protectedareaoccurrences;
    }

    public void setProtectedareaoccurrences(String protectedareaoccurrences) {
        this.protectedareaoccurrences = protectedareaoccurrences;
    }
}
