ALTER TABLE darwin_core  
  ADD taxon_id character varying DEFAULT '-',
  ADD scientific_name_id character varying DEFAULT '-',
  ADD accepted_name_usage_id character varying DEFAULT '-',
  ADD parent_name_usage_id character varying DEFAULT '-',
  ADD original_name_usage_id character varying DEFAULT '-',
  ADD name_according_to_id character varying DEFAULT '-',
  ADD name_published_in_id character varying DEFAULT '-',
  ADD taxon_concept_id character varying DEFAULT '-',
  ADD parent_name_usage character varying DEFAULT '-',
  ADD original_name_usage character varying DEFAULT '-',
  ADD name_according_to character varying DEFAULT '-',
  ADD name_published_in character varying DEFAULT '-',
  ADD taxonomic_status character varying DEFAULT '-',
  ADD nomenclatural_status character varying DEFAULT '-',
  ADD occurence_id character varying DEFAULT '-',
  ADD occurence_details character varying DEFAULT '-',
  ADD individual_id character varying DEFAULT '-',
  ADD establishment_means character varying DEFAULT '-',
  ADD occurence_status character varying DEFAULT '-',
  ADD event_id character varying DEFAULT '-',
  ADD location_id character varying DEFAULT '-',
  ADD higher_geography_id character varying DEFAULT '-',
  ADD identification_id character varying DEFAULT '-';
  
